package de.xmap.jiracloud;

public class FieldOption {
    private String id;
    private String value;
    private boolean disabled;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public boolean isDisabled() {
        return disabled;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }
}
/* Wenn ich die Contexts abfragen möchte:
get("/rest/api/3/field/customfield_10140/contexts");
  {
  "maxResults": 20,
  "startAt": 0,
  "total": 1,
  "isLast": true,
  "values": [
    {
      "id": 10287,
      "name": "Default Configuration Scheme for Features",
      "description": "Default configuration scheme generated by Jira",
      "associatedIssueTypes": [],
      "associatedProjects": [],
      "isAllProjects": true,
      "isAllIssueTypes": true
    }
  ]
}
*/